{% set name = "runstats" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grantjenks/python-runstats/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 48a0cd627ee5e854990960ca8920a789922fe7477d0c6d469f9f5baf6e007294

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
  host:
    - python
    - tox
    - cython
    - pip
  run:
    - python

test:
  imports:
    - runstats
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest tests -vs -n auto --cov-branch --cov-fail-under=100 --cov-report=term-missing --cov=runstats
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytest-xdist

about:
  home: http://www.grantjenks.com/docs/runstats/
  summary: Compute statistics and regression in one pass
  dev_url: https://github.com/grantjenks/python-runstats
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
